# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BombKit-Example' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BombKit-Example
  pod 'BombKit', :path => '../'
  target 'BombKit-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
