# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2
script:
- xctool -project BombKit.xcodeproj -scheme "BombKit" test -sdk iphonesimulator
- xctool -project BombKit.xcodeproj -scheme "BombKit OSX" test -sdk macosx
- xctool -project BombKit.xcodeproj -scheme "BombKit tvOS" test -sdk appletvsimulator